spring:
  redis:
    host: server
    database: 0
  application:
    name: udp-socket-application
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  udp:
    server-port: 8880
    buff-size: 50